dell-asm/razor-server

tasks/redhat.task/post_install.erb

The /etc/ntp.conf file that ASM was writing contained an invalid
option "nopeernoquery". This reworks that code to just modify the
default ntp.conf file by commenting out the server entries and
adding in the one specified in the installer options.

ASM-3064 Fix ntp configuration for RHEL/CentOS

---

tasks/vmware_esxi.task/ks.cfg.erb

command used for starting the service and adding it to the start-up list was not correct. Old commands were applicable for ESX not ESXi and these were part of original ESXi kickstart template file.

NTP Configuration for ESXi

---

tasks/redhat.task/post_install.erb
tasks/windows2008.task/default-unattended.xml.erb
tasks/windows2008.task/hyper-v-unattended.xml.erb
tasks/windows2012.task/default-unattended.xml.erb
tasks/windows2012.task/hyper-v-unattended.xml.erb

The razor task scripts were calculating the correct puppet agent
certificate name to use based off of the first word in the
hostname. This certificate name has to match that used in
asm-deployer in order for the correct puppet configuration to be
applied to the node. In the case where the FQDN was used as the
hostname the certificate name calculated on the razor side was
incorrect because it missed the domain name. It's not possible to
just use the fqdn when calculating the agent certificate name
because the original hostname specified by the user may not have
been an FQDN.
This commit adds agent_certname to the razor policy
installer_options. The razor task scripts use that option which
guarantees that they are using the same certificate name that
asm-deployer uses.

ASM-3312 support fqdn hostnames

---

lib/razor/initialize.rb

Older versions of Sequel gems do not catch DB exceptions in the case
where the DB fails and so Razor just don't work after a DB restart
or connection interrupt.
Version 4.6.0 of Sequel has a patch to handle this better but Razor
requires 4.3.x due to some incompatibilities.
We can upgrade Sequel and it seems the Razor team has done so in
RAZOR-70 but they are only going up to 4.9 which is not a version we
have
So we can either install 4.9.0 on the appliance and carry a patch to
take us to that version Gem or apply the patch in this commit.  I think
rather than install more versions of sequel - which do not seem to come
from RPMs - this is probably the less complicated route at least until
we upgrade Razor again
This commit activates regular rechecking of the connection in Razor,
should …

ASM-3272: Handle postgres failures better

---

lib/razor/data.rb

We had a case where the try loop retried infinitely and filled up 48GB
of logs.  This limits that to just 10 maximum tries

ASM-3413: Handle infinite retry loop case

---

tasks/windows2012.task/default-unattended.xml.erb
tasks/windows2012.task/hyper-v-unattended.xml.erb

Puppet agent 3.4.3 is installed on Windows nodes that has the support for getting the facts of failover cluster network. Puppet agent run fails on the HyperV nodes where failover cluster feature is installed.

ASM-2476 Puppet agent fails on hyper-v host after configuration

---

tasks/windows2012.task/default-unattended.xml.erb
tasks/windows2012.task/hyper-v-unattended.xml.erb

Windows unattended files are updated to use version 3.3.2 instead of the latest 3.6.2 version to re-enable end to end Windows VM and HyperV installation.
Will revert to the latest puppet agent installation when we are able to find a workable solution for unattended installation or we move to new Windows broker model.

ASM-4093 Revert windows puppet agent 3.6.2 changes

---

build-winpe/build-razor-winpe.ps1

If user enters "DHCP" instead of an ASM appliance IP, we'll build the .iso to point to the DHCP server as the razor server.

ASM 3584 - Add DHCP option to build-razor-winpe script

---

Gemfile

This was causing the appliance not to use the dell-asm-util gem that
was already installed; instead bundle install always tried to fetch
from github which failed.
This means that the gem will have to be manually installed for now.

ASM-1973 do not specify git location for dell-asm-util

---

tasks/vmware_esxi.task/ks.cfg.erb

This was causing issues with racks.  ESXi, for some reason, doesn't see the virtual disks being created as local.

ASM-5262 Removed firstdisk specifier for local on esxi kickstart.

---

tasks/redhat.task/post_install.erb

Puppet installation on RHEL / CentOS 7.2 was failing because
libselinux-ruby was already installed. This commit checks if it is
already installed and skips it if so.
In future we need to move to using yum to install the puppet agent so
that problems like this don't occur. It would also allow us to support
minimal ISOs that don't include samba support.

ASM-5492 skip libselinux-ruby if already installed

---

tasks/redhat.task/post_install.erb

Newer C-series servers like the C6320 include an iDrac so hard drive
monitoring should be done through that. This change skips the NRPE
configuration that was used for hard drive monitoring of e.g. C6220
servers.

Skip NRPE config for redhat on new C6320 servers

---

tasks/redhat.task/post_install.erb

RHEL 7 issue, the stale puppet agent lock file not being cleaned up at reboot, is fixed
systemd unit script is used instead of crontab
modifying service_deployment.rb and/or puppet modules did not help, using razor post_install.sh to clean up the lock file instead

ASM-5580 clean up puppet lock file if no process is running

---

tasks/vmware_esxi.task/boot.cfg.erb

In order to complete an ESXi install in environments where DHCP is not
availalbe we need to have the static IP information passed to the ESXi
installer as a kernel option.

ASM-5141 set static IP info in esxi boot.cfg

---

tasks/vmware_esxi.task/boot.cfg.erb

This ensures we are using the NIC that was configured with the PXE
network during the OS install. Also added the DNS server if available.

ASM-5141 specify NIC in ESXi boot.cfg

---

tasks/redhat.task/kernel_args.erb
tasks/redhat.task/kickstart.erb
tasks/vmware_esxi.task/boot.cfg.erb

Add support for StaticIP to be used for razor install on RHEL and CentOS.
Uses the network_config object passed into the node metadata.

ASM-5142 StaticIP support for Linux ISO install

---

tasks/vmware_esxi.task/ks.cfg.erb

When the reboot command is issued during ESXi install the installer
tries to eject the CD. In recent versions of iDrac that will cause
virtual media to become disconnected. Work around by passing the
--noeject argument.

ASM-6647 Do not eject CD after ESXi install

---

tasks/redhat.task/post_install.erb

The final step of the redhat post_install script is to remove itself
from /etc/rc.d/rc.local so that it doesn't get re-run when the server
next reboots. However it's possible for it to execute twice if the
server gets rebooted while it is running. In that case it was adding a
duplicate dellasm hosts file entry. That will cause problems later on
if e.g. you use puppet to manage that entry. In that case puppet will
only update the second of the entries and the server will continue to
use the first IP.

ASM-6906 Do not set hosts entry if already set

---

tasks/redhat.task/kickstart.erb

The conditional for FIRST_PERC_VOL was incorrect to cause device
capture to never happen for VM's

ASM-6905-2 Fix first volume RAID selection for VM

---

tasks/suse11.task/post_install.erb

Needed to back rev puppet agent install to use version
3.6 of the agent instead of 3.8.

ASM-6621 Update puppet agent for Suse 11

---

tasks/vmware_esxi.task/ks.cfg.erb

Created partition label to MSDOS for back-plane disk which are labels as "ATA" in disk enumeration. This will ensure we are just creating the partition for local back-place disk

ASM-7035 VSAN deployment fails with VSAN partition on back side disk

---

tasks/redhat.task/kickstart.erb
tasks/redhat.task/post_install.erb

Centos 6.7 .iso can't install libselinux-ruby and kickstart is not
behaving properly so for centos/redhat 6 installs we'll install
libselinux-ruby with the puppet agent depending on the version of
libselinux installed
This pull request should be merged with: https://github.com/dell-asm/asm-automation/pull/483

ASM-7174 CentOS 6.7 OS fails complaining libselinux-ruby-xxx.rpm missing

---

tasks/windows2012.task/hyper-v-unattended.xml.erb

Update the NTP configuration on the server as part of OS installation so that puppet check-in happens with correct time configuration.

ASM-7011 Update NTP configuration for HyperV server during initial installation

---

tasks/redhat.task/post_install.erb
tasks/suse11.task/post_install.erb
tasks/windows2008.task/default-unattended.xml.erb
tasks/windows2012.task/default-unattended.xml.erb
tasks/windows2012.task/hyper-v-unattended.xml.erb

Updated timeout to 10 minutes while installing puppet agent on Server / VM. This will ensure we have correct timeout value on all supported operating system

ASM-7450 Increase puppet config timeout

---

tasks/vmware_esxi.task/ks.cfg.erb

Checked-in code has an typo. Due to which kickstart include statement was not included.

ASM-7220 ESXi installation is failing on R730XD in case there are additonal SATA disks on the server

---

tasks/windows2012.task/default-unattended.xml.erb

Change the unattend order on windows 2012 to sync the NTP time before
running puppet.  We've found that a time sync with a running puppet
agent can cause the agent to hang

ASM-7644 Sync the NTP time before puppet run

---

tasks/vmware_esxi.task/ks.cfg.erb

The model exposed by SATADOM drives seems to have spaces, causing
clearpart and install commands to fail for the ATA disks.
The solution to this problem is to fix the space issue by quoting the
model value.

ASM-7503 ESXi razor task change to support SATADOM boot option

---

tasks/windows2008.task/default-unattended.xml.erb
tasks/windows2012.task/default-unattended.xml.erb

This commit addresses the issue where the ntp service interferes
with the puppet-agent process on the Windows 2008 and 2012. When
the interference occurs, the puppet-agent is stuck indefinitely
until the system time catches up to new time set by the ntp service.
This typically takes a few hours to sync, so the deployment times
out and fails.
In order to resolve this issue, default-unattended.xml.erb files for
the Windows 2008 and 2012 are updated. The RunSynchronous commands
are rearranged to configure the ntp service before installing and
configuring the puppet service. Additionally, the ntp service is
set to start up at the system startup while the puppet service is
set to start after other system services (including the ntp) to
reduce the possibility of the interference.
The validation …

ASM-7709 setup ntp before puppet config

---

tasks/vmware_esxi.task/ks.cfg.erb

Clearing VSAN partition from all disks used for deployment. This will help in eliminate VSAN disk partition before using the server for any new VSAN deployment.

ASM-7920 VSAN Deployment Fails under certain disk conditions

---

tasks/common/puppet_conf.erb
tasks/redhat.task/post_install.erb
tasks/suse11.task/post_install.erb
tasks/suse12.task/post_install.erb

By default, puppet runs are 30 minutes. Sometimes, that causes wastage of
time for ASM needed configuration in worst case scenarios. We reduce the
runinterval to 5 minutes so that this wastage is minimized.
Also we moved duplicated puppet.conf lines into common place.
Note: There will be another PR later for windows install.

ASM-8050 Set initial puppet run interval to 5 minutes for linux installs

---

tasks/vmware_esxi.task/ks.cfg.erb

Previously stage_done_url was unable to get invoked because of the
firewall settings. This results in installed flag beeign not set with
polocy.
This PR changes the order of stage_done_url beeing called so that
installed flag will assigned with polocy after installing esxi successfully.

ASM-8011: Reordered stage_done_url for esxi to make sure it is invoked.

---

tasks/windows2008.task/default-unattended.xml.erb
tasks/windows2012.task/default-unattended.xml.erb

By default, puppet runs are 30 minutes. Sometimes, that causes wastage of
time for ASM needed configuration in worst case scenarios. We reduce the
runinterval to 5 minutes so that this wastage is minimized.
Note: commit 402a14eaa02d0d3f35479f0f6ad9bcd742a1a6ee introduced the same
behavior for linux installs.

ASM-8050 Set initial puppet run interval to 5 minutes for windows

---

tasks/vmware_esxi.task/ks.cfg.erb

For FC630 All flash deployment, we need to install ESXi on virtual disk managed by H330 PERC controller. Now along with now ATA disks used for R730XD servers we will use Dell Serial disk for OS installations too.

ASM-7916 Add ability to deploy FC430 and FC630 VSAN ready nodes OS to  local disk instead of SD card

---

tasks/vmware_esxi.task/ks.cfg.erb

On VMware shell, script is executed as normal shell instead of bash shell. Script changes added recently was not working as a result the last ATA disk in the enumeration is selected for the OS installation. Updated the script based on "SHELL" to ensure we select the correct disk device.

ASM- 8293 ESXi VSAN SATADOM deployment is installing ESXi on different disk

---

tasks/vmware_esxi.task/ks.cfg.erb

Previously for ESXI6.5 firewall was enable by default which would time out
stage_done call.
This PR will disable the firewall and make sure it will call stage_done
url. Later firewall is enable again.

ASM-8255: Disables the Firewall which is on by default

---

tasks/vmware_esxi.task/ks.cfg.erb

if test condition was missing a space at the end, leading to Shell script failure. Updated script to ensure all checks are applied to the servers

ASM-8293 ESXi VSAN SATADOM deployment is installing ESXi on different disk

---

tasks/vmware_esxi.task/ks.cfg.erb

The ESXi installer tries to determine the disk to use for OS
installation for VSAN_AHCI deployments by looking for disks with
names like "Local ATA Disk" or "DELL Serial". But PERC RAID volumes
are named "Local DELL Disk". Therefore the installer was failing to
find the install disk for VSAN_AHCI deployments to servers with RAID
volumes.

ASM-8322 Allow VSAN deployment to RAID volume

---

tasks/vmware_esxi.task/ks.cfg.erb

Esxi 6.5 deployments to the SD card were failing due to the wrong
argument being used to specify USB storage for the installation
location

ASM-8325 Fix Esxi 6.5 SD installs

---

tasks/vmware_esxi.task/ks.cfg.erb

For FC630 servers we need to perform the OS installation on virtual disk. This disk is presented to ESXi with Dell Serial or Local DELL Diks pattern. Updated pattern check for selection of the disk

ASM-8332 VSAN Deployment to FC630 with RAID VD fails

---

tasks/vmware_esxi.task/ks.cfg.erb

During ESXi installation removed all existing VMFS partition to ensure all disks are available for VSAN deployment. This will also help for SD card and Satadom installation where previous ESXi installation datastores will be wiped off.

ASM-8383 VMFS Datastore not deleted on all disks in VSAN

---

tasks/vmware_esxi.task/ks.cfg.erb

Skipped clean-up operations for remote disks. For remote disk these cleanup operation commands are taking too long to complete leading to a substantial delay in OS installation

ASM-8444 ESXi installation needs to skip datastore cleanup for remote volumes

---

tasks/redhat.task/post_install.erb

For RHEL/CentOS 7.3, different versions of rpm packages must be
installed during the razor post install process. Required packages
are added in asm-automation under asm-automation/razorRpm/files/
puppet-agent/rhel7/x86_64/ directory. These files should be placed
in /var/lib/razor/repo-store/puppet-agent/rhel7/x86_64/rhel7_3
directory of the ASM appliance.
UPDATE: RHEL 7.3 baremetal does not get net-utils package installed
through the OS packages. Now the script checks and installs the
package where necessary.

ASM-8553 support for RHEL/CentOS 7.3 added

---

tasks/redhat.task/kickstart.erb

Previously os was installed to hardisk, However adding CD drive makes
OS to get installed on cd drive and fail to find installer files.
This PR will select the hard_disk device by selecting last line of the
command output to select drive.

ASM-8648: supports os_install on vm with CD/DVD drive

---

tasks/windows2008.task/default-unattended.xml.erb
tasks/windows2008.task/hyper-v-unattended.xml.erb
tasks/windows2012.task/default-unattended.xml.erb
tasks/windows2012.task/hyper-v-unattended.xml.erb

By default the Windows w32time (NTP) service if set to Auto start is
actually set to Auto (triggered). And the default trigger is when the
domain service starts. Therefore in cases where the server is not
joined to a domain the service never starts up after reboot. This
behavior and workaround is document in the Microsoft support article
[Windows Time service doesn't start automatically on a workgroup
computer that's running Windows 7 or Windows Server 2008 R2][1].
Additionally the timezone setting in the Windows unattended.xml file
seems to be applied after the `<RunSynchronous>` commands are
executed. We use the `<RunSycnhronous>` commands to configure
NTP. Therefore NTP starts (and presumably sets the correct time) and
then the timezone is changed which changes the system time. Since …

ASM-9173 Set Windows w32time start trigger

---

tasks/suse11.task/autoyast.erb
tasks/suse11.task/post_install.erb
tasks/suse12.task/autoyast.erb
tasks/suse12.task/post_install.erb

Because ntp is setup and started in the autoyast section, it originally
cannot resolve the dellasm hostname.  Need to restart ntp service
in the postinstall to ensure it can resolve dellasm
Also, ntpq -p returns: **No association ID's returned** when it is running in chroot jails
due to lack of needed files

ASM-8323 Using dellasm as ntp server failing

---

tasks/redhat.task/post_install.erb

For certain RHEL 7.3 and CentOS 7.3 ISO's, the "--replacepkgs" opt
is not enough. Certain files may be in conflict. In such a case,
we also need "--replacefiles" opt.

ASM-9640 updated rpm installation with additional force opt

---

tasks/redhat.task/post_install.erb

For RHEL/CentOS 7.3, there is a known bug that causes the puppet
service to run before the network is fully up. For most modules,
this won't be a real issue since puppet agent will retry again
later. However, this causes a problem for network module since
this module will try to rewrite the configurations and restart
the service, which results in misconfigured network service and
locked down service status for both network and puppet.
To fix this issue, the razor post_install script will now create
the custom puppet.service systemd script with network-online.target
for Requires and After sections in the service unit descriptor.

ASM-9663 add network-online dependency to puppet.service

---

tasks/common/puppet_conf.erb
tasks/redhat.task/post_install.erb

ASM-77(A) fix for puppet configuration template
This commit includes fix for the puppet configuration template,
which is used by the razor post_install script. There are also
other minor fixes in the post_install script itself to let
RHEL deployments to work until puppet.broker is implemented to
meet the overall requirement of this ticket.

Lud 77 - A: puppet configuration file location fix

---

tasks/redhat.task/post_install.erb

This is a small change in the razor post_install script to support
puppet installation on CentOS 7.4 VM.

ASM-9853 deploy CentOS 7.4 VM

---

tasks/redhat.task/kickstart.erb
tasks/redhat.task/post_install.erb

The CentOS ISO contains both the default RPM packages and GPG keys and
is available via razor's HTTP repo_url. This change sets that up as
the only enabled yum repository on a default CentOS install. This will
allow "yum install" commands to work out of the box even if the node
has no external internet access. This will make it easier to customize
the OS for different appliaction flows.

Point to razor OS repo URL as default yum repo

---

brokers/ludwig-puppet.broker/install.erb
tasks/redhat.task/post_install.erb

Previously razor's `repo_url` was used to create a yum repository
pointing to the RHEL/CentOS repository files included on the
ISO. However that URL typically has an internal PXE IP which may not
be accessible by the node after the PXE network is removed.
Instead define and use an `/etc/hosts` file entry that points to the
internal PXE IP. It will be updated later on if needed by puppet
configuration when the PXE network is removed. The repository URL can
then use the `hosts` file entry instead of the IP directly.

LUD-547 Use dellasm hostname for razor-internal EL repo

---

tasks/vmware_esxi.task/ks.cfg.erb

Add additional log location for debugging issue where local datastore cannot be renamed

LUD-552 Redeploy ScaleIO to SATADOM server without teardown fails due to datastore name

---

tasks/redhat.task/post_install.erb

The OS repository was added as a yum repo for the redhat installer but
the GPG key was hard-coded to the CentOS one. This allows it to work
for RHEL also.

VXFM-2413 Pick correct GPG key for RHEL or CentOS

---

brokers/puppet.broker/install.erb

There was code in the puppet broker to run ntpdate against the broker
`ntpdate_server` but it wasn't working due to using wrong ERB syntax.

VXFM-3518 Run ntpdate prior to installing puppet

---

brokers/puppet.broker/install.erb

Don't allow NTP synchronization errors to entirely abort the puppet
broker script. There is a good chance it can still succeed.

VXFM-3624 Disable exit on error while synchronizing NTP

---

tasks/redhat.task/kickstart.erb

Clear all the partitions from the server before initiating the OS installation. This will take care of all stale partitions from previous installation

VXFM-3514 Partitions on drives with HBA330 causes adding them to VxFlex OS to fail

---

tasks/redhat.task/kickstart.erb

For storage only servers, disk cleanup code was working after last refactoring where we tried to reuse a file created in "pre" installation stage in post-installation stage. Looks like, the file created in the pre-installation stage is deleted and it is no longer available in the post-installation stage

VXFM-6181 Partitions not cleared from storage-only disk

---

tasks/redhat.task/post_install.erb

sg3_utils generally resides in the ISO Packages which are configured
as a yum repository called `razor-internal`. But it was being
installed before `razor-internal was created.

VXFM-8883 Install sg3_utils after razor repo created
